from sqlmodel import SQLModel, Field
from typing import Optional
from datetime import datetime

class DecisionFeedbackBase(SQLModel):
    transaction_id: str = Field(..., description="The original transaction ID from the scoring request.")
    alert_id: str = Field(..., description="The internal alert ID generated by the Cognize platform.")
    original_decision: str = Field(..., description="The verdict initially issued by the platform (APPROVE/CHALLENGE/DECLINE).")
    final_bank_outcome: str = Field(..., description="The final ground-truth label from the bank (e.g., FRAUD_CONFIRMED, FALSE_POSITIVE).")
    analyst_label: str = Field(..., description="A human-readable label or classification provided by the investigator.")
    notes: Optional[str] = Field(None, description="Detailed explanatory notes from the fraud investigation team.")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="The date and time the feedback was recorded.")

class DecisionFeedback(DecisionFeedbackBase, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)

class DecisionFeedbackCreate(DecisionFeedbackBase):
    pass
